"""Creando tablas

Revision ID: c861fa05241b
Revises: 
Create Date: 2025-06-24 18:49:01.742288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c861fa05241b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('rh', sa.String(length=5), nullable=True),
    sa.Column('ciudad_expedicion', sa.String(length=100), nullable=True),
    sa.Column('ciudad_nacimiento', sa.String(length=100), nullable=True),
    sa.Column('ciudad_domicilio', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('ofertas_laborales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordenes_contratacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('examenes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asociaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidato_id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('fecha_asociacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidatos.id'], ),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas_laborales.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_contratacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asociaciones')
    op.drop_table('ordenes_contratacion')
    op.drop_table('ofertas_laborales')
    op.drop_table('candidatos')
    # ### end Alembic commands ###
